{"ip": "localhost", "app": "python-common", "level": "INFO", "trace": "", "filepath": "/home/qianlinwu.wu/pydemo/logging_custom/custom_logging.py", "line_number": "120", "time": "2021-08-20 17:58:15,439", "message": "info  level log", "stack_trace": "None"}
{"ip": "localhost", "app": "python-common", "level": "ERROR", "trace": "[Errno 2] No such file or directory: '/path/to/does/not/exist'", "filepath": "/home/qianlinwu.wu/pydemo/logging_custom/custom_logging.py", "line_number": "124", "time": "2021-08-20 17:58:15,439", "message": "file exception", "stack_trace": "Traceback (most recent call last):   File '/home/qianlinwu.wu/pydemo/logging_custom/custom_logging.py', line 122, in <module>     open('/path/to/does/not/exist', 'rb') FileNotFoundError: [Errno 2] No such file or directory: '/path/to/does/not/exist'"}
